In general, datasets which contain marketing data can be used for 2 different business goals:

1. Prediction of the results of the marketing campaign for each customer and clarification of factors which affect the campaign results. This helps to find out the ways how to make marketing campaigns more efficient.

2. Finding out customer segments, using data for customers, who subscribed to term deposit. This helps to identify the profile of a customer, who is more likely to acquire the product and develop more targeted marketing campaigns.

In [ ]:
import pandas as pd,numpy as np

In [ ]:
from google.colab import files
data=files.upload()

Saving bank dataset 1.xlsx to bank dataset 1 (1).xlsx


In [ ]:
df=pd.read_excel("bank dataset 1.xlsx")

In [ ]:
df

age           job  marital  education default  balance housing loan  \
0      58    management  married   tertiary      no     2143     yes   no   
1      44    technician   single  secondary      no       29     yes   no   
2      33  entrepreneur  married  secondary      no        2     yes  yes   
3      47   blue-collar  married    unknown      no     1506     yes   no   
4      33       unknown   single    unknown      no        1      no   no   
...   ...           ...      ...        ...     ...      ...     ...  ...   
9034   52     housemaid  married    primary      no     1340      no   no   
9035   57    technician  married    primary      no       67      no   no   
9036   23      services  married  secondary      no     2673     yes   no   
9037   44      services  married  secondary      no      382      no   no   
9038   40   blue-collar  married  secondary      no     6536      no   no   

      contact  day month  duration  campaign  pdays  previous poutcome   y  
0     unknown    5   may       261         1     -1         0  unknown  no  
1     unknown    5   may       151         1     -1         0  unknown  no  
2     unknown    5   may        76         1     -1         0  unknown  no  
3     unknown    5   may        92         1     -1         0  unknown  no  
4     unknown    5   may       198         1     -1         0  unknown  no  
...       ...  ...   ...       ...       ...    ...       ...      ...  ..  
9034  unknown    5   jun       175         1     -1         0  unknown  no  
9035  unknown    5   jun        67         1     -1         0  unknown  no  
9036  unknown    5   jun        81         2     -1         0  unknown  no  
9037  unknown    5   jun      1167         1     -1         0  unknown  no  
9038  unknown    5   jun       647         1     -1         0  unknown  no  

[9039 rows x 17 columns]

In [ ]:
dfcopy=df.copy()#shallow copy

EDA

In [ ]:
df.shape

(9039, 17)

In [ ]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [ ]:
df.tail()

age          job  marital  education default  balance housing loan  \
9034   52    housemaid  married    primary      no     1340      no   no   
9035   57   technician  married    primary      no       67      no   no   
9036   23     services  married  secondary      no     2673     yes   no   
9037   44     services  married  secondary      no      382      no   no   
9038   40  blue-collar  married  secondary      no     6536      no   no   

      contact  day month  duration  campaign  pdays  previous poutcome   y  
9034  unknown    5   jun       175         1     -1         0  unknown  no  
9035  unknown    5   jun        67         1     -1         0  unknown  no  
9036  unknown    5   jun        81         2     -1         0  unknown  no  
9037  unknown    5   jun      1167         1     -1         0  unknown  no  
9038  unknown    5   jun       647         1     -1         0  unknown  no

In [ ]:
df.iloc[22:67]

age            job   marital  education default  balance housing loan  \
22   32    blue-collar    single    primary      no       23     yes  yes   
23   25       services   married  secondary      no       50     yes   no   
24   40        retired   married    primary      no        0     yes  yes   
25   44         admin.   married  secondary      no     -372     yes   no   
26   39     management    single   tertiary      no      255     yes   no   
27   52   entrepreneur   married  secondary      no      113     yes  yes   
28   46     management    single  secondary      no     -246     yes   no   
29   36     technician    single  secondary      no      265     yes  yes   
30   57     technician   married  secondary      no      839      no  yes   
31   49     management   married   tertiary      no      378     yes   no   
32   60         admin.   married  secondary      no       39     yes  yes   
33   59    blue-collar   married  secondary      no        0     yes   no   
34   51     management   married   tertiary      no    10635     yes   no   
35   57     technician  divorced  secondary      no       63     yes   no   
36   25    blue-collar   married  secondary      no       -7     yes   no   
37   53     technician   married  secondary      no       -3      no   no   
38   36         admin.  divorced  secondary      no      506     yes   no   
39   37         admin.    single  secondary      no        0     yes   no   
40   44       services  divorced  secondary      no     2586     yes   no   
41   50     management   married  secondary      no       49     yes   no   
42   60    blue-collar   married    unknown      no      104     yes   no   
43   54        retired   married  secondary      no      529     yes   no   
44   58        retired   married    unknown      no       96     yes   no   
45   36         admin.    single    primary      no     -171     yes   no   
46   58  self-employed   married   tertiary      no     -364     yes   no   
47   44     technician   married  secondary      no        0     yes   no   
48   55     technician  divorced  secondary      no        0      no   no   
49   29     management    single   tertiary      no        0     yes   no   
50   54    blue-collar   married  secondary      no     1291     yes   no   
51   48     management  divorced   tertiary      no     -244     yes   no   
52   32     management   married   tertiary      no        0     yes   no   
53   42         admin.    single  secondary      no      -76     yes   no   
54   24     technician    single  secondary      no     -103     yes  yes   
55   38   entrepreneur    single   tertiary      no      243      no  yes   
56   38     management    single   tertiary      no      424     yes   no   
57   47    blue-collar   married    unknown      no      306     yes   no   
58   40    blue-collar    single    unknown      no       24     yes   no   
59   46       services   married    primary      no      179     yes   no   
60   32         admin.   married   tertiary      no        0     yes   no   
61   53     technician  divorced  secondary      no      989     yes   no   
62   57    blue-collar   married    primary      no      249     yes   no   
63   33       services   married  secondary      no      790     yes   no   
64   49    blue-collar   married    unknown      no      154     yes   no   
65   51     management   married   tertiary      no     6530     yes   no   
66   60        retired   married   tertiary      no      100      no   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
22  unknown    5   may       160         1     -1         0  unknown  no  
23  unknown    5   may       342         1     -1         0  unknown  no  
24  unknown    5   may       181         1     -1         0  unknown  no  
25  unknown    5   may       172         1     -1         0  unknown  no  
26  unknown    5   may       296         1     -1         0  unknown  no  
27  unknown

In [ ]:
df.iloc[888]

age                  32
job          management
marital         married
education      tertiary
default              no
balance             233
housing             yes
loan                 no
contact         unknown
day                   7
month               may
duration            193
campaign              1
pdays                -1
previous              0
poutcome        unknown
y                    no
Name: 888, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9039 entries, 0 to 9038
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        9039 non-null   int64 
 1   job        9039 non-null   object
 2   marital    9039 non-null   object
 3   education  9039 non-null   object
 4   default    9039 non-null   object
 5   balance    9039 non-null   int64 
 6   housing    9039 non-null   object
 7   loan       9039 non-null   object
 8   contact    9039 non-null   object
 9   day        9039 non-null   int64 
 10  month      9039 non-null   object
 11  duration   9039 non-null   int64 
 12  campaign   9039 non-null   int64 
 13  pdays      9039 non-null   int64 
 14  previous   9039 non-null   int64 
 15  poutcome   9039 non-null   object
 16  y          9039 non-null   object
dtypes: int64(7), object(10)
memory usage: 1.2+ MB


In [ ]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [ ]:
df.describe()

age       balance          day     duration     campaign  \
count  9039.000000   9039.000000  9039.000000  9039.000000  9039.000000   
mean     39.245602   1037.630822    15.959066   263.617767     2.609581   
std       9.253832   2491.121967     9.037007   248.916075     2.951275   
min      20.000000  -3372.000000     2.000000     0.000000     1.000000   
25%      32.000000     39.000000     8.000000   116.000000     1.000000   
50%      38.000000    332.000000    15.000000   192.000000     2.000000   
75%      46.000000   1059.000000    26.000000   322.000000     3.000000   
max      61.000000  58544.000000    30.000000  3366.000000    63.000000   

        pdays  previous  
count  9039.0    9039.0  
mean     -1.0       0.0  
std       0.0       0.0  
min      -1.0       0.0  
25%      -1.0       0.0  
50%      -1.0       0.0  
75%      -1.0       0.0  
max      -1.0       0.0

data cleaning

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
df["y"].unique()

array(['no', 'yes'], dtype=object)

In [ ]:
#x,y split
x=df.drop(columns="y",axis=1)
y=df["y"]

In [ ]:
x

age           job  marital  education default  balance housing loan  \
0      58    management  married   tertiary      no     2143     yes   no   
1      44    technician   single  secondary      no       29     yes   no   
2      33  entrepreneur  married  secondary      no        2     yes  yes   
3      47   blue-collar  married    unknown      no     1506     yes   no   
4      33       unknown   single    unknown      no        1      no   no   
...   ...           ...      ...        ...     ...      ...     ...  ...   
9034   52     housemaid  married    primary      no     1340      no   no   
9035   57    technician  married    primary      no       67      no   no   
9036   23      services  married  secondary      no     2673     yes   no   
9037   44      services  married  secondary      no      382      no   no   
9038   40   blue-collar  married  secondary      no     6536      no   no   

      contact  day month  duration  campaign  pdays  previous poutcome  
0     unknown    5   may       261         1     -1         0  unknown  
1     unknown    5   may       151         1     -1         0  unknown  
2     unknown    5   may        76         1     -1         0  unknown  
3     unknown    5   may        92         1     -1         0  unknown  
4     unknown    5   may       198         1     -1         0  unknown  
...       ...  ...   ...       ...       ...    ...       ...      ...  
9034  unknown    5   jun       175         1     -1         0  unknown  
9035  unknown    5   jun        67         1     -1         0  unknown  
9036  unknown    5   jun        81         2     -1         0  unknown  
9037  unknown    5   jun      1167         1     -1         0  unknown  
9038  unknown    5   jun       647         1     -1         0  unknown  

[9039 rows x 16 columns]

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9039 entries, 0 to 9038
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        9039 non-null   int64 
 1   job        9039 non-null   object
 2   marital    9039 non-null   object
 3   education  9039 non-null   object
 4   default    9039 non-null   object
 5   balance    9039 non-null   int64 
 6   housing    9039 non-null   object
 7   loan       9039 non-null   object
 8   contact    9039 non-null   object
 9   day        9039 non-null   int64 
 10  month      9039 non-null   object
 11  duration   9039 non-null   int64 
 12  campaign   9039 non-null   int64 
 13  pdays      9039 non-null   int64 
 14  previous   9039 non-null   int64 
 15  poutcome   9039 non-null   object
dtypes: int64(7), object(9)
memory usage: 1.1+ MB


data encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()

In [ ]:
for i in x.columns:
    if x[i].dtype=='object':
        x[i] =  l.fit_transform(x[i])

y=df['y']=l.fit_transform(df['y'])

In [ ]:
x

age  job  marital  education  default  balance  housing  loan  contact  \
0      58    4        1          2        0     2143        1     0        0   
1      44    9        2          1        0       29        1     0        0   
2      33    2        1          1        0        2        1     1        0   
3      47    1        1          3        0     1506        1     0        0   
4      33   11        2          3        0        1        0     0        0   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
9034   52    3        1          0        0     1340        0     0        0   
9035   57    9        1          0        0       67        0     0        0   
9036   23    7        1          1        0     2673        1     0        0   
9037   44    7        1          1        0      382        0     0        0   
9038   40    1        1          1        0     6536        0     0        0   

      day  month  duration  campaign  pdays  previous  poutcome  
0       5      1       261         1     -1         0         0  
1       5      1       151         1     -1         0         0  
2       5      1        76         1     -1         0         0  
3       5      1        92         1     -1         0         0  
4       5      1       198         1     -1         0         0  
...   ...    ...       ...       ...    ...       ...       ...  
9034    5      0       175         1     -1         0         0  
9035    5      0        67         1     -1         0         0  
9036    5      0        81         2     -1         0         0  
9037    5      0      1167         1     -1         0         0  
9038    5      0       647         1     -1         0         0  

[9039 rows x 16 columns]

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 0])

TRAIN,TEST SPLIT

In [ ]:
#test,train split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=29)

STANDATIZATION

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

In [ ]:
x_train

array([[-0.79709577,  0.04869555,  1.39669928, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.60749159,  0.04869555, -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.60749159, -1.145478  , -1.90558634, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.79598859,  0.34723894,  1.39669928, ...,  0.        ,
         0.        ,  0.        ],
       [-1.44536686, -0.84693461, -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.06726568, -0.84693461, -0.25444353, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
x_test

array([[-0.68905059, -0.84693461, -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       [-0.79709577,  1.54141249, -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       [-0.25686986,  0.94432572, -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.49944641, -1.145478  , -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       [-0.79709577, -0.84693461, -0.25444353, ...,  0.        ,
         0.        ,  0.        ],
       [-0.47296023,  1.54141249, -1.90558634, ...,  0.        ,
         0.        ,  0.        ]])

MODEL TRAIN

In [ ]:
#import and tree classifer
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(random_state=1234)
dtc.fit(x_train,y_train)

DecisionTreeClassifier(random_state=1234)

TEST MODEL

In [ ]:
#test model
y_predict=dtc.predict(x_test)

In [ ]:
y_predict

array([0, 0, 0, ..., 0, 0, 0])

EVALUATE THE MODEL

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_predict)
score = dtc.score(x_test, y_test)
print(cm)
print(score)
cr=classification_report(y_test, y_predict)
print(cr)

[[2550   82]
 [  44   36]]
0.9535398230088495
              precision    recall  f1-score   support

           0       0.98      0.97      0.98      2632
           1       0.31      0.45      0.36        80

    accuracy                           0.95      2712
   macro avg       0.64      0.71      0.67      2712
weighted avg       0.96      0.95      0.96      2712



DATA SET 2

In [ ]:
from google.colab import files
data2=files.upload()

Saving bank dataset 2.xlsx to bank dataset 2.xlsx


In [ ]:
df2=pd.read_excel("bank dataset 2.xlsx")

In [ ]:
df2copy=df2.copy()

In [ ]:
df2.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#x,y split
x2=df2.drop(columns="y",axis=1)
y2=df2["y"]

In [ ]:
x2

age          job   marital  education default  balance housing loan  \
0      44   technician   married  secondary      no      533      no   no   
1      59      retired  divorced    primary      no      -88     yes   no   
2      45   management   married  secondary      no        0      no   no   
3      38       admin.    single    unknown      no       13      no   no   
4      48      retired    single  secondary      no     3458      no   no   
...   ...          ...       ...        ...     ...      ...     ...  ...   
9035   60      retired   married    primary      no        0      no   no   
9036   37  blue-collar   married    primary      no       11      no   no   
9037   51       admin.   married  secondary     yes     -160      no  yes   
9038   59   management   married   tertiary      no     1308      no   no   
9039   60    housemaid   married    primary      no      726      no  yes   

        contact  day month  duration  campaign  pdays  previous poutcome  
0       unknown    5   jun        74         1     -1         0  unknown  
1       unknown    5   jun       910         2     -1         0  unknown  
2       unknown    5   jun        65         2     -1         0  unknown  
3       unknown    5   jun        21         1     -1         0  unknown  
4       unknown    5   jun       292         1     -1         0  unknown  
...         ...  ...   ...       ...       ...    ...       ...      ...  
9035  telephone   30   jul       130         3     -1         0  unknown  
9036  telephone   30   jul       109         8     -1         0  unknown  
9037   cellular   30   jul       118         4     -1         0  unknown  
9038   cellular   30   jul       183         4     -1         0  unknown  
9039   cellular   30   jul        94         5     -1         0  unknown  

[9040 rows x 16 columns]

In [ ]:
y2

0        no
1       yes
2        no
3        no
4        no
       ... 
9035     no
9036     no
9037     no
9038     no
9039     no
Name: y, Length: 9040, dtype: object

data encoding

In [ ]:
for i in x2.columns:
    if x2[i].dtype=='object':
        x2[i] =  l.fit_transform(x2[i])

y2=df2['y']=l.fit_transform(df2['y'])

In [ ]:
x2

age  job  marital  education  default  balance  housing  loan  contact  \
0      44    9        1          1        0      533        0     0        2   
1      59    5        0          0        0      -88        1     0        2   
2      45    4        1          1        0        0        0     0        2   
3      38    0        2          3        0       13        0     0        2   
4      48    5        2          1        0     3458        0     0        2   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
9035   60    5        1          0        0        0        0     0        1   
9036   37    1        1          0        0       11        0     0        1   
9037   51    0        1          1        1     -160        0     1        0   
9038   59    4        1          2        0     1308        0     0        0   
9039   60    3        1          0        0      726        0     1        0   

      day  month  duration  campaign  pdays  previous  poutcome  
0       5      1        74         1     -1         0         0  
1       5      1       910         2     -1         0         0  
2       5      1        65         2     -1         0         0  
3       5      1        21         1     -1         0         0  
4       5      1       292         1     -1         0         0  
...   ...    ...       ...       ...    ...       ...       ...  
9035   30      0       130         3     -1         0         0  
9036   30      0       109         8     -1         0         0  
9037   30      0       118         4     -1         0         0  
9038   30      0       183         4     -1         0         0  
9039   30      0        94         5     -1         0         0  

[9040 rows x 16 columns]

In [ ]:
y2

array([0, 1, 0, ..., 0, 0, 0])

STANDATIZATION

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x2 = ss.transform(x2)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [ ]:
x2

array([[ 4.40000000e+01,  9.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.90000000e+01,  5.00000000e+00, -1.06126582e-16, ...,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.50000000e+01,  4.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 5.10000000e+01,  2.35836849e-17,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.90000000e+01,  4.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.00000000e+01,  3.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

test model

In [ ]:
y_predict2=dtc.predict(x2)

In [ ]:
y_predict2

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y2, y_predict2)
score = dtc.score(x2, y2)
print(cm)
print(score)
cr=classification_report(y2,y_predict2)
print(cr)

[[   0 8532]
 [   0  508]]
0.05619469026548673
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      8532
           1       0.06      1.00      0.11       508

    accuracy                           0.06      9040
   macro avg       0.03      0.50      0.05      9040
weighted avg       0.00      0.06      0.01      9040



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DATA SET 3

In [ ]:
from google.colab import files
data3=files.upload()

Saving bank dataset 3.xlsx to bank dataset 3.xlsx


In [ ]:
df3=pd.read_excel("bank dataset 3.xlsx")

In [ ]:
df3

age           job   marital  education default  balance housing loan  \
0      41       unknown   married    unknown      no      779      no   no   
1      32      services   married  secondary      no      -31      no  yes   
2      54    technician   married  secondary      no      114      no   no   
3      41      services   married  secondary      no     1785      no   no   
4      26   blue-collar    single  secondary      no      179      no   no   
...   ...           ...       ...        ...     ...      ...     ...  ...   
9035   49    technician   married  secondary      no     8689      no   no   
9036   43  entrepreneur    single   tertiary      no     5347      no   no   
9037   51     housemaid  divorced  secondary      no      330      no   no   
9038   52    management   married   tertiary      no     6873     yes   no   
9039   43    management   married   tertiary      no     2100     yes   no   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   30   jul       647        10     -1         0  unknown   no  
1     telephone   30   jul        96         6     -1         0  unknown   no  
2      cellular   30   jul       458         3     -1         0  unknown  yes  
3      cellular   30   jul       225         7     -1         0  unknown   no  
4      cellular   30   jul       103         3     -1         0  unknown   no  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
9035   cellular   21   nov       586         1     -1         0  unknown   no  
9036   cellular   21   nov       189         3     -1         0  unknown   no  
9037  telephone   21   nov       218         3     -1         0  unknown   no  
9038   cellular   21   nov       235         2     -1         0  unknown   no  
9039   cellular   21   nov       105         1     -1         0  unknown   no  

[9040 rows x 17 columns]

In [ ]:
df3.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#x,y split
x3=df3.drop(columns="y",axis=1)
y3=df3["y"]

data  encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()

In [ ]:
for i in x3.columns:
    if x3[i].dtype=='object':
        x3[i] =  l.fit_transform(x3[i])

y3=df3['y']=l.fit_transform(df3['y'])

In [ ]:
x3

age           job   marital  education default  balance housing loan  \
0      41       unknown   married    unknown      no      779      no   no   
1      32      services   married  secondary      no      -31      no  yes   
2      54    technician   married  secondary      no      114      no   no   
3      41      services   married  secondary      no     1785      no   no   
4      26   blue-collar    single  secondary      no      179      no   no   
...   ...           ...       ...        ...     ...      ...     ...  ...   
9035   49    technician   married  secondary      no     8689      no   no   
9036   43  entrepreneur    single   tertiary      no     5347      no   no   
9037   51     housemaid  divorced  secondary      no      330      no   no   
9038   52    management   married   tertiary      no     6873     yes   no   
9039   43    management   married   tertiary      no     2100     yes   no   

        contact  day month  duration  campaign  pdays  previous poutcome  
0      cellular   30   jul       647        10     -1         0  unknown  
1     telephone   30   jul        96         6     -1         0  unknown  
2      cellular   30   jul       458         3     -1         0  unknown  
3      cellular   30   jul       225         7     -1         0  unknown  
4      cellular   30   jul       103         3     -1         0  unknown  
...         ...  ...   ...       ...       ...    ...       ...      ...  
9035   cellular   21   nov       586         1     -1         0  unknown  
9036   cellular   21   nov       189         3     -1         0  unknown  
9037  telephone   21   nov       218         3     -1         0  unknown  
9038   cellular   21   nov       235         2     -1         0  unknown  
9039   cellular   21   nov       105         1     -1         0  unknown  

[9040 rows x 16 columns]

In [ ]:
y3

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x3= ss.transform(x3)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [ ]:
x3

array([[ 4.10000000e+01,  1.10000000e+01,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 3.20000000e+01,  7.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 5.40000000e+01,  9.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       ...,
       [ 5.10000000e+01,  3.00000000e+00, -6.00822449e-17, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 5.20000000e+01,  4.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 4.30000000e+01,  4.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00]])

test model


In [ ]:
y_predict3=dtc.predict(x3)

In [ ]:
y_predict3

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y3, y_predict3)
score = dtc.score(x3, y3)
print(cm)
print(score)
cr=classification_report(y3,y_predict3)
print(cr)

[[   2 8485]
 [   0  553]]
0.06139380530973451
              precision    recall  f1-score   support

           0       1.00      0.00      0.00      8487
           1       0.06      1.00      0.12       553

    accuracy                           0.06      9040
   macro avg       0.53      0.50      0.06      9040
weighted avg       0.94      0.06      0.01      9040



DATA SET 4

In [ ]:
from google.colab import files
data4=files.upload()

Saving bank dataset 4.xlsx to bank dataset 4.xlsx


In [ ]:
df4=pd.read_excel("bank dataset 4.xlsx")

In [ ]:
df4

age            job   marital  education default  balance housing loan  \
0      40         admin.   married    primary      no       72     yes  yes   
1      31     management    single   tertiary      no      528      no  yes   
2      46  self-employed   married    primary      no     3155     yes   no   
3      46       services   married  secondary      no     2948      no   no   
4      37         admin.  divorced  secondary      no     1533     yes   no   
...   ...            ...       ...        ...     ...      ...     ...  ...   
9035   33         admin.   married  secondary      no      177     yes   no   
9036   51    blue-collar   married  secondary      no     3370     yes   no   
9037   30     management  divorced   tertiary     yes    -1105     yes   no   
9038   55       services   married  secondary      no      761     yes   no   
9039   33      housemaid   married  secondary      no      826     yes   no   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   21   nov       849         1     -1         0  unknown  yes  
1      cellular   21   nov         5         7     -1         0  unknown   no  
2      cellular   21   nov       271         1     -1         0  unknown   no  
3      cellular   21   nov       893         1     -1         0  unknown  yes  
4      cellular   21   nov       555         4     -1         0  unknown  yes  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
9035   cellular   11   may       100         1     -1         0  unknown   no  
9036   cellular   11   may        59         1     -1         0  unknown   no  
9037   cellular   11   may       686         1     -1         0  unknown   no  
9038  telephone   11   may        28         1     -1         0  unknown   no  
9039   cellular   11   may       256         1     -1         0  unknown   no  

[9040 rows x 17 columns]

In [ ]:
df4.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#x,y split
x4=df4.drop(columns="y",axis=1)
y4=df4["y"]

data encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()

In [ ]:
for i in x4.columns:
    if x4[i].dtype=='object':
        x4[i] =  l.fit_transform(x4[i])

y4=df4['y']=l.fit_transform(df4['y'])

In [ ]:
x4

age  job  marital  education  default  balance  housing  loan  contact  \
0      40    0        1          0        0       72        1     1        0   
1      31    4        2          2        0      528        0     1        0   
2      46    6        1          0        0     3155        1     0        0   
3      46    7        1          1        0     2948        0     0        0   
4      37    0        0          1        0     1533        1     0        0   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
9035   33    0        1          1        0      177        1     0        0   
9036   51    1        1          1        0     3370        1     0        0   
9037   30    4        0          2        1    -1105        1     0        0   
9038   55    7        1          1        0      761        1     0        1   
9039   33    3        1          1        0      826        1     0        0   

      day  month  duration  campaign  pdays  previous  poutcome  
0      21      6       849         1     -1         0         3  
1      21      6         5         7     -1         0         3  
2      21      6       271         1     -1         0         3  
3      21      6       893         1     -1         0         3  
4      21      6       555         4     -1         0         3  
...   ...    ...       ...       ...    ...       ...       ...  
9035   11      5       100         1     -1         0         3  
9036   11      5        59         1     -1         0         3  
9037   11      5       686         1     -1         0         3  
9038   11      5        28         1     -1         0         3  
9039   11      5       256         1     -1         0         3  

[9040 rows x 16 columns]

In [ ]:
y4

array([1, 0, 0, ..., 0, 0, 0])

STANDATIZATION

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x4 = ss.transform(x4)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [ ]:
x4

array([[ 4.00000000e+01,  3.14449132e-17,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 3.10000000e+01,  4.00000000e+00,  2.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 4.60000000e+01,  6.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       ...,
       [ 3.00000000e+01,  4.00000000e+00, -9.88268702e-17, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 5.50000000e+01,  7.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 3.30000000e+01,  3.00000000e+00,  1.00000000e+00, ...,
        -1.00000000e+00,  0.00000000e+00,  3.00000000e+00]])

test model

In [ ]:
y_predict4=dtc.predict(x4)
y_predict4

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y4, y_predict4)
score = dtc.score(x4, y4)
print(cm)
print(score)
cr=classification_report(y4,y_predict4)
print(cr)

[[   0 7973]
 [   0 1067]]
0.11803097345132743
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      7973
           1       0.12      1.00      0.21      1067

    accuracy                           0.12      9040
   macro avg       0.06      0.50      0.11      9040
weighted avg       0.01      0.12      0.02      9040



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


DATA SET 5

In [ ]:
from google.colab import files
data5=files.upload()

Saving bank dataset 5.xlsx to bank dataset 5.xlsx


In [ ]:
df5=pd.read_excel("bank dataset 5.xlsx")

In [ ]:
df5

age            job   marital  education default  balance housing loan  \
0      43       services    single  secondary      no      518     yes   no   
1      40    blue-collar    single    primary      no        0     yes  yes   
2      24       services   married  secondary      no     4500     yes   no   
3      47    blue-collar   married  secondary      no       71     yes   no   
4      30  self-employed    single   tertiary      no      137     yes   no   
...   ...            ...       ...        ...     ...      ...     ...  ...   
9046   25     technician    single  secondary      no      505      no  yes   
9047   51     technician   married   tertiary      no      825      no   no   
9048   71        retired  divorced    primary      no     1729      no   no   
9049   72        retired   married  secondary      no     5715      no   no   
9050   57    blue-collar   married  secondary      no      668      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome    y  
0      cellular   11   may       295         1    370         1  failure   no  
1      cellular   11   may       114         2     -1         0  unknown   no  
2      cellular   11   may       733         2     -1         0  unknown  yes  
3      cellular   11   may       170         1    370         1  failure   no  
4      cellular   11   may       214         1     -1         0  unknown   no  
...         ...  ...   ...       ...       ...    ...       ...      ...  ...  
9046   cellular   17   nov       386         2     -1         0  unknown  yes  
9047   cellular   17   nov       977         3     -1         0  unknown  yes  
9048   cellular   17   nov       456         2     -1         0  unknown  yes  
9049   cellular   17   nov      1127         5    184         3  success  yes  
9050  telephone   17   nov       508         4     -1         0  unknown   no  

[9051 rows x 17 columns]

In [ ]:
df5.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#x,y split
x5=df5.drop(columns="y",axis=1)
y5=df5["y"]

data encoding

In [ ]:
for i in x5.columns:
    if x5[i].dtype=='object':
        x5[i] =  l.fit_transform(x5[i])

y5=df5['y']=l.fit_transform(df5['y'])

In [ ]:
x5

age  job  marital  education  default  balance  housing  loan  contact  \
0      43    7        2          1        0      518        1     0        0   
1      40    1        2          0        0        0        1     1        0   
2      24    7        1          1        0     4500        1     0        0   
3      47    1        1          1        0       71        1     0        0   
4      30    6        2          2        0      137        1     0        0   
...   ...  ...      ...        ...      ...      ...      ...   ...      ...   
9046   25    9        2          1        0      505        0     1        0   
9047   51    9        1          2        0      825        0     0        0   
9048   71    5        0          0        0     1729        0     0        0   
9049   72    5        1          1        0     5715        0     0        0   
9050   57    1        1          1        0      668        0     0        1   

      day  month  duration  campaign  pdays  previous  poutcome  
0      11      8       295         1    370         1         0  
1      11      8       114         2     -1         0         3  
2      11      8       733         2     -1         0         3  
3      11      8       170         1    370         1         0  
4      11      8       214         1     -1         0         3  
...   ...    ...       ...       ...    ...       ...       ...  
9046   17      9       386         2     -1         0         3  
9047   17      9       977         3     -1         0         3  
9048   17      9       456         2     -1         0         3  
9049   17      9      1127         5    184         3         2  
9050   17      9       508         4     -1         0         3  

[9051 rows x 16 columns]

In [ ]:
y5

array([0, 0, 1, ..., 1, 1, 0])

STANDATIZATION

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x5 = ss.transform(x5)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(


In [ ]:
x5

array([[ 3.91401228e-01,  9.44325718e-01,  1.39669928e+00, ...,
         3.71000000e+02,  1.00000000e+00,  0.00000000e+00],
       [ 6.72656822e-02, -8.46934608e-01,  1.39669928e+00, ...,
         0.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [-1.66145723e+00,  9.44325718e-01, -2.54443534e-01, ...,
         0.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       ...,
       [ 3.41666632e+00,  3.47238942e-01, -1.90558634e+00, ...,
         0.00000000e+00,  0.00000000e+00,  3.00000000e+00],
       [ 3.52471150e+00,  3.47238942e-01, -2.54443534e-01, ...,
         1.85000000e+02,  3.00000000e+00,  2.00000000e+00],
       [ 1.90403377e+00, -8.46934608e-01, -2.54443534e-01, ...,
         0.00000000e+00,  0.00000000e+00,  3.00000000e+00]])

test model

In [ ]:
y_predict5=dtc.predict(x5)
y_predict5

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
# Evaluate the model
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y5, y_predict5)
score = dtc.score(x5, y5)
print(cm)
print(score)
cr=classification_report(y5,y_predict5)
print(cr)

[[   2 6191]
 [   0 2858]]
0.31598718373660367
              precision    recall  f1-score   support

           0       1.00      0.00      0.00      6193
           1       0.32      1.00      0.48      2858

    accuracy                           0.32      9051
   macro avg       0.66      0.50      0.24      9051
weighted avg       0.78      0.32      0.15      9051

